### ISSUE TITLE
Proposal: Start Page for easy access

### ISSUE THREAD

**Issue by apvarun** [excalidraw/excalidraw-desktop#154]
**Feature request**

To show start page when excalidraw desktop app opens. 
- Allows to open recent files quickly
- Decide whether to start a new sketch or to open existing from file

**Sample Wireframe:**
![Excalidraw Desktop Start Page](https://user-images.githubusercontent.com/8411309/82529009-52ee9f80-9b3a-11ea-8e26-a68eb8658a31.png)

@lipis @pinussilvestrus Would like to hear your opinion on this.

**Comment by pinussilvestrus** [comment]
Thanks for your thoughts! I'm wondering whether this is Something better to have for the Main Application instead of the Desktop App?

**Comment by dwelle** [comment]
> I'm wondering whether this is Something better to have for the Main Application instead of the Desktop App?

One of our main principles (not published publicly yet) is to reduce friction and time-to-first-draw as much as possible, and that means no welcome screens.

It's tempting (in the early days, I wanted to implement one as well), but currently it would add more cost (UX-wise) than it would add value.

As for desktop app, I think we should govern it by the same principles, but I don't have that strong an opinion on this, so will defer to @lipis and others. The recently-opened makes sense here (unlike for the web, currently).

**Comment by apvarun** [comment]
The motivation behind opening this discussion is that, people usually download something only when it able to provide more functionality, if it is used numerous times a day or want to offline. In such cases, it would be common to switch between multiple documents/sketches.

Having tabs in the main application might be an answer but still, for a native app, providing options from menus to open recent files is a common behaviour, if not a start page.

**Comment by dwelle** [comment]
That makes sense. I can see how having a list of recently opened documents would indeed be very useful for a desktop app.

That said, it'd have to implemented here, not in the web app.

I'd also think some more whether we want a full-blown welcome screen, or some other way to list recent files (maybe a picker or something similar to https://github.com/excalidraw/excalidraw/pull/583 which was later removed from the web app --- it wouldn't have to be identical, just an idea).

I personally don't use the desktop app (yet), so I'm not very invested. Thus, what I say here are just pointers. @pinussilvestrus @lipis viewpoints have more value here.

**Comment by pinussilvestrus** [comment]
Maybe a list / menu option for recently opened files would be a good first iteration.

I'd also not go for a huge starting screen for that purpose to keep the quick-start feeling

**Comment by j-f1** [comment]
For reference, here’s what Xcode opens on launch:

![image](https://user-images.githubusercontent.com/25517624/82583844-a0cace00-9b61-11ea-8b6b-5d8506f96510.png)
