### ISSUE TITLE
Resave files to the same destination

### ISSUE THREAD

**Issue by qimingweng** [excalidraw/excalidraw-desktop#165]
When you load a .excalidraw file, and then make some changes, and then save again, it should save to the same file, rather than save as a new file and force you to rename it.

**Comment by lipis** [comment]
Most likely this will be solved in the core app: https://github.com/excalidraw/excalidraw/pull/1709

**Comment by tomayac** [comment]
When your browser supports the Native File System API, then yes, this will be fixed with https://github.com/excalidraw/excalidraw/pull/1709.

**Comment by dwelle** [comment]
And by "your browser" we mean when we upgrade to Electron 9 which ships with chrome 83. https://github.com/excalidraw/excalidraw-desktop/issues/172
