### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-desktop#17]
- [ ] macOS: https://github.com/excalidraw/excalidraw-logo/blob/master/excalidraw.icns
- [ ] Windows: https://github.com/excalidraw/excalidraw-logo/blob/master/excalidraw.ico
- [ ] Linux: ?

**Comment by pinussilvestrus** [comment]
https://www.electron.build/icons

**Comment by lipis** [comment]
Could you create those in the `excalidraw-logo` repo?

**Comment by lipis** [comment]
Or maybe here first, and then we can move them accordignly.
