### ISSUE TITLE
Upload app to App Store

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-desktop#21]
I guess @vjeux will have to create an Apple Developers account eventually to be able to do that.

**Comment by vjeux** [comment]
Why does it have to be me?

**Comment by j-f1** [comment]
I have an Apple Developer account I can publish on if nobody else does.

**Comment by lipis** [comment]
> Why does it have to be me?

You are the boss :)

**Comment by vjeux** [comment]
Haha. I have never published an app to the app store, i don’t even know if I have a dev account. Jed account or anyone else is fine :)

**Comment by lipis** [comment]
But you know.. if we gonna [hit by a bus](https://en.wikipedia.org/wiki/Bus_factor) you should be able to continue publishing 🤣

**Comment by j-f1** [comment]
There seems to be a way to add additional users with access to my account, but I’ve never used it so I don’t really know how it would work.

**Comment by j-f1** [comment]
When we’re ready to distribute, I just need a first & last name and an Apple ID email to add someone to the app.

**Comment by lipis** [comment]
Not sure how it works, but it would be nice to have published by Excalidraw instead of a username.. Can we create a company first and add people that could publish it?

**Comment by j-f1** [comment]
We need to get a DUNS number which requires having an actual business to have a name other than my legal name attached to it on the App Store: https://developer.apple.com/programs/enroll/

Then we’d need to get a second developer program subscription which is $99/yr

**Comment by lipis** [comment]
If we can't get that DUNS number, then I would use @vjeux's as he is more popular on Twitter :D Plus he is the boss..
