### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-desktop#23]
## Overview

- https://excalidraw.com/#json=5176497841111040,3fsAWaZz8kfgPh2SzloeHA

![excalidraw-202022901618 (1)](https://user-images.githubusercontent.com/125676/75595515-0d678c80-5a8d-11ea-9817-cf66fd821045.png)

## Initial open

- [x] Contains a local copy of Excalidraw app
- [x] Loads it and works offline

## Open the app

- [x] Loads local version of Exaclidraw app
- [ ] Periodically checks in the background for newer versions: [version.json](https://excalidraw.com/version.json)
- [ ] If newer version is different than the local one then download latest `asar` packaged from the above URL
- [ ] Unpack the contents
- [ ] Ask user to reload the app to get the latest features

## On Excalidraw.com side

- [x] Version can be generated on the build and stored as timestamp: `2020-02-28-21-50-45` in `version.json` (the actual format is up to debate)

- [x] Serve the version: [`https://excalidraw.com/version.json`](https://excalidraw.com/version.json)
  ```jsonc
  {
    "app": "excalidraw-2020-02-28-21-50-45.asar",
    "version": "2020-02-28-21-50-45"
  }
  ```
- [x] Serve downloadable app: `https://excalidraw.com/excalidraw-2020-02-28-21-50-45.asar`

**Comment by pinussilvestrus** [comment]
It sounds good in theory. Practically we will have to investigate whether it's feasible to update the wrapped Excalidraw web app directly on the artifact on the user's machine.

Normally you would bundle update the local version with the artifacts on every release of the desktop app. Not sure whether this will work with auto-updating.

Firstly will we have to see how to integrate the app (as `zip` or `npm`) into the electron app.

**Comment by pinussilvestrus** [comment]
I created a first version of using a local packed Excalidraw bundle: https://github.com/excalidraw/excalidraw-desktop/commit/9b25168ec1cd3001e468a015311fd699fadb837c

Seems like some files can't be found:

![image](https://user-images.githubusercontent.com/9433996/75605587-644c8080-5ae4-11ea-85d4-655008d25e9b.png)

But when I unpack the `.asar` file locally, the missing files are there. Will have a look what's going on

**Comment by pinussilvestrus** [comment]
Seems like they searching for the required file inside the root directory:

![image](https://user-images.githubusercontent.com/9433996/75605926-ebe7be80-5ae7-11ea-8d02-c29edfb126b5.png)
