### ISSUE TITLE
Download a zip file of the latest excalidraw and serve the files locally so it can work offline.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-desktop#3]
Maybe for version 2, instead of loading directly from `https://excalidraw.com` we should serve them locally if exist.

- [ ] Generate zip file and upload somewhere
- [ ] Load app from local files if exist
- [ ] In the background, check regularly for newer versions of the zip file
- [ ] On start if there is a newer version downloaded and not installed, install it
- [ ] Notify user if there is a new version to reload from the latest zip file

**Comment by Fausto95** [comment]
If we add Auto update, we could add the main repo here and keep it sync so that way if we make new releases, the app would just get the newer versions

**Comment by lipis** [comment]
Not sure how it could work.

**Comment by j-f1** [comment]
I’m guessing just bundle the Excalidraw code into the desktop app?

**Comment by pinussilvestrus** [comment]
> I’m guessing just bundle the Excalidraw code into the desktop app?

+1

Let's create a simple client which uses the Excalidraw web app code locally
