### ISSUE TITLE
Show current version in application menu

### ISSUE THREAD

**Issue by pinussilvestrus** [excalidraw/excalidraw-desktop#44]
Once we implemented #43, we could show the local version of Excalidraw the application menu

**Comment by shrirambalaji** [comment]
@pinussilvestrus I've added an About Menu Item, with the Version. Should clicking on the version item, lead to a webpage - maybe https://excalidraw.com/version.json ? I think it should ideally redirect to changelog / releases section of excalidraw.

Also currently, the version string seems to be the last updated date. IMO it'd be great to have it [semver](https://semver.org/) compliant.

![about-menu-item-excalidraw-desktop](https://user-images.githubusercontent.com/11358903/79046666-f097aa80-7c2f-11ea-923f-b19e5b4095fe.gif)

**Comment by pinussilvestrus** [comment]
Looks good!

Would be fine with linking to the Version file for now. @lipis what do you think?

**Comment by lipis** [comment]
I was thinking something like that: 
<img width="416" alt="Screenshot 2020-04-11 at 6 23 31 PM" src="https://user-images.githubusercontent.com/125676/79047797-9ee82380-7c21-11ea-8a5d-1c475a0ed9b6.png">

Version of the electron app, and version of the web app which is a date in our case. There is no sem ver.

**Comment by shrirambalaji** [comment]
@lipis Okay, I'll add a dialogue that opens up and shows up this Version Info on click.

**Comment by lipis** [comment]
Should be in the top left menu: 
<img width="271" alt="Screenshot 2020-04-11 at 6 33 56 PM" src="https://user-images.githubusercontent.com/125676/79048044-081c6680-7c23-11ea-938c-f4c6323dd072.png">

**Comment by shrirambalaji** [comment]
@lipis should the app version be the same as package.json's version string?

**Comment by lipis** [comment]
I guess..

**Comment by shrirambalaji** [comment]
Hmm, the unpacked `.asar` doesn't seem to have a package.json file in `dist/client`.

**Comment by lipis** [comment]
Excalidraw version: 2020-04-11-16-18-08
Desktop Version: https://github.com/excalidraw/excalidraw-desktop/blob/master/package.json#L59

**Comment by shrirambalaji** [comment]
So I'll just parse the file from github master for now then? But I guess that'd be the remote's latest desktop app version, whereas the user's local client might be on an older appVersion. Please Correct me if I'm wrong @pinussilvestrus @lipis

**Comment by lipis** [comment]
Yeap.. these are two different options..

**Comment by shrirambalaji** [comment]
@lipis @pinussilvestrus I've implemented the about dialog box, and it looks something like this. Fyi, I'm not adding React to the desktop app, as vanilla js seems good enough for now.

![excalidraw-show-version](https://user-images.githubusercontent.com/11358903/79056609-f2845c80-7c75-11ea-9e43-3e5907317b87.gif)

**Comment by pinussilvestrus** [comment]
Closed via #100
